# Generated by Django 2.1.7 on 2019-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('product_img', models.ImageField(default='images/default.jpeg', upload_to='images/')),
            ],
        ),
    ]
